// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AdvanceHourReducer from "../advance_hour_reducer";
import CreateFighterReducer from "../create_fighter_reducer";
import CreateTournamentReducer from "../create_tournament_reducer";
import HostTournamentReducer from "../host_tournament_reducer";
import PlaceBetReducer from "../place_bet_reducer";
import PlaceBidReducer from "../place_bid_reducer";
import RegisterUserReducer from "../register_user_reducer";
import SponsorFighterReducer from "../sponsor_fighter_reducer";
import StartTournamentReducer from "../start_tournament_reducer";
import VerifyLoginReducer from "../verify_login_reducer";

export type AdvanceHourParams = __Infer<typeof AdvanceHourReducer>;
export type CreateFighterParams = __Infer<typeof CreateFighterReducer>;
export type CreateTournamentParams = __Infer<typeof CreateTournamentReducer>;
export type HostTournamentParams = __Infer<typeof HostTournamentReducer>;
export type PlaceBetParams = __Infer<typeof PlaceBetReducer>;
export type PlaceBidParams = __Infer<typeof PlaceBidReducer>;
export type RegisterUserParams = __Infer<typeof RegisterUserReducer>;
export type SponsorFighterParams = __Infer<typeof SponsorFighterReducer>;
export type StartTournamentParams = __Infer<typeof StartTournamentReducer>;
export type VerifyLoginParams = __Infer<typeof VerifyLoginReducer>;

