// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  tournamentId: __t.u32().name("tournament_id"),
  x: __t.u8(),
  y: __t.u8(),
  tileType: __t.string().name("tile_type"),
  hasResource: __t.bool().name("has_resource"),
  resourceType: __t.option(__t.string()).name("resource_type"),
});
