// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  fighterId: __t.u32().name("fighter_id"),
  openedBy: __t.identity().name("opened_by"),
  startedAt: __t.timestamp().name("started_at"),
  endsAtMicros: __t.u64().name("ends_at_micros"),
  settled: __t.bool(),
});
