// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  userId: __t.identity().name("user_id"),
  tournamentId: __t.u32().name("tournament_id"),
  fighterId: __t.u32().name("fighter_id"),
  betType: __t.string().name("bet_type"),
  amount: __t.f64(),
  odds: __t.f64(),
  status: __t.string(),
  placedAt: __t.timestamp().name("placed_at"),
});
