// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  tournamentId: __t.u32().name("tournament_id"),
  hour: __t.u32(),
  eventType: __t.string().name("event_type"),
  description: __t.string(),
  involvedIds: __t.string().name("involved_ids"),
  x: __t.option(__t.u8()),
  y: __t.option(__t.u8()),
  timestamp: __t.timestamp(),
});
