// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  tournamentId: __t.u32().name("tournament_id"),
  userId: __t.identity().name("user_id"),
  fighterId: __t.u32().name("fighter_id"),
  itemType: __t.string().name("item_type"),
  cost: __t.f64(),
  status: __t.string(),
  dropX: __t.option(__t.u8()).name("drop_x"),
  dropY: __t.option(__t.u8()).name("drop_y"),
  queuedHour: __t.u32().name("queued_hour"),
  deliveryHour: __t.u32().name("delivery_hour"),
});
