// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  tournamentId: __t.u32().name("tournament_id"),
  fighterId: __t.u32().name("fighter_id"),
  isAlive: __t.bool().name("is_alive"),
  x: __t.u8(),
  y: __t.u8(),
  hunger: __t.u8(),
  thirst: __t.u8(),
  fatigue: __t.u8(),
  injury: __t.u8(),
  morale: __t.u8(),
  condition: __t.string(),
  inventory: __t.string(),
  alliances: __t.string(),
  kills: __t.u8(),
  eliminatedHour: __t.option(__t.u32()).name("eliminated_hour"),
});
