// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  name: __t.string(),
  arenaType: __t.string().name("arena_type"),
  status: __t.string(),
  currentHour: __t.u32().name("current_hour"),
  gridWidth: __t.u8().name("grid_width"),
  gridHeight: __t.u8().name("grid_height"),
  prizePool: __t.f64().name("prize_pool"),
  hostIdentity: __t.option(__t.identity()).name("host_identity"),
  createdAt: __t.timestamp().name("created_at"),
});
